# Generated by Django 5.2.8 on 2025-11-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_reserva_created_at_alter_reserva_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='rut',
            field=models.CharField(max_length=20),
        ),
    ]
