# Generated by Django 5.2.8 on 2025-11-19 23:26

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_reserva_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='rut',
            field=models.CharField(max_length=20, validators=[app.validators.validar_rut]),
        ),
    ]
